####### BOOTSTRAP ########
ansible_user: dataops
initial_user: root
bootstrap_user: dataops
backup_user: dataops_backup
github_pubkeys:
  - Bee0933

upgrade_all_packages: false
docker_users: "{{bootstrap_user}}"
docker_daily_prune: true

base_dir: /home/{{ bootstrap_user }}


# Airflow
airflow_src_dir: "../../airflow"
airflow_dir: "{{ base_dir }}/airflow"
airflow_user: dataops
airflow_password: dataops

# traefik
traefik_airflow_mail: mailbox@mail.airflow.bestnyah.xyz
traefik_airflow_host: airflow.bestnyah.xyz
traefik_flower_host: flower.bestnyah.xyz
# traefik_node_exporter_host: exporter.bestnyah.xyz


# Node Exporter
node_exporter_container_name: node_exporter
node_exporter_container_image: prom/node-exporter:v1.5.0 
node_exporter_container_env: {}
node_exporter_local_port: 9100
node_exporter_container_stop_timeout: "30"

# prometheus
container_name_prometheus: prometheus
prometheus_container_imagename: prom/prometheus
prometheus_container_image_tag: latest
prometheus_config_container_dir: /etc/prometheus
metrics_auth_user: dataops
prometheus_web_port: 9090
prometheus_config_dir: "{{base_dir}}/prometheus"
prometheus_target_dir: "{{prometheus_config_dir}}/targets"
prometheus_target_project_name: sftp-platform
target_template: "targets.yml"
rules_template: "rules.yml"
target_group: "all"
alertmanager_url: 127.0.0.1:{{alertmanager_web_port}}

# grafana
grafana_image: "grafana/grafana-enterprise"
grafana_image_tag: latest
grafana_container_name: "grafana"
grafana_base_dir: "/home/{{ ansible_user }}/grafana"
grafana_data_dir: "{{ grafana_base_dir }}/data"
grafana_config_dir: "{{ grafana_base_dir }}/config"
grafana_provisioning_base_dir: "{{ grafana_base_dir }}/provisioning/"
provisoning_dashboard_dir: "{{ grafana_provisioning_base_dir }}/dashboards"
provisoning_datasource_dir: "{{ grafana_provisioning_base_dir }}/datasources"
grafana_dashboards_dir: "{{ grafana_base_dir }}/dashboards"
grafana_port: "3000"
grafana_admin_user: "dataops"
grafana_admin_password: "dataops"  
device: device
grafana_prometheus_datasource: prometheus