####### BOOTSTRAP ########
ansible_user: dataops
initial_user: root
bootstrap_user: dataops
backup_user: dataops_backup
github_pubkeys:
  - Bee0933

upgrade_all_packages: false
docker_users: "{{bootstrap_user}}"
docker_daily_prune: true

base_dir: /home/{{ ansible_user }}


# Airflow
airflow_src_dir: "../../airflow"
airflow_dir: "{{ base_dir }}/airflow"
airflow_user: dataops
airflow_password: dataops

# traefik
traefik_airflow_mail: mailbox@mail.airflow.bestnyah.xyz
traefik_airflow_host: airflow.bestnyah.xyz
traefik_flower_host: flower.bestnyah.xyz
# traefik_node_exporter_host: exporter.bestnyah.xyz


# Node Exporter
node_exporter_container_name: node_exporter
node_exporter_container_image: prom/node-exporter:v1.5.0 
node_exporter_container_env: {}
node_exporter_local_port: 9100
node_exporter_container_stop_timeout: "30"
node_exporter_container_networks:
  - name: host