####### BOOTSTRAP ########
ansible_user: dataops
initial_user: root
bootstrap_user: dataops
backup_user: dataops_backup
github_pubkeys:
  - Bee0933

upgrade_all_packages: false
docker_users: "{{bootstrap_user}}"
docker_daily_prune: true

base_dir: /home/{{ bootstrap_user }}


# Airflow
airflow_src_dir: "../../airflow"
airflow_dir: "{{ base_dir }}/airflow"
airflow_user: dataops
airflow_password: dataops
additional_pip_requirements: "praw boto3 pandas fastparquet snowflake-sqlalchemy soda-core-snowflake soda-core-scientific"

# soda
soda_snowflake_user: SODA_USER
soda_snowflake_password: dataops
soda_snowflake_account: llbozwk-fw33224 


# traefik
traefik_dir: "{{ base_dir }}/traefik"
traefik_image: traefik:3.0.1
traefik_monitor_server_docker_container_name: traefik-monitor-server
traefik_monitor_server_docker_network: confluent 
traefik_airflow_server_docker_network: confluent 
traefik_airflow_mail: mailbox@mail.airfloww.bestnyah.xyz
traefik_monitor_mail: mailbox@mail.monitor.bestnyah.xyz
traefik_airflow_host: airfloww.bestnyah.xyz
traefik_node_exporter_0_host: exporter0.bestnyah.xyz
traefik_prometheus_host: prometheus.bestnyah.xyz
traefik_alertmanager_host: alertmanager.bestnyah.xyz
traefik_loki_host: loki.bestnyah.xyz
traefik_grafana_host: grafana.bestnyah.xyz
traefik_basic_auth_user: "dataops"
traefik_basic_auth_password: "dataops"
traefik_basic_auth_encrypt_password: "$2y$05$cMZrdRrLS2OaF7oCrvNqaOq3.WaKXwW2H24RIIlZkYR4LnwnfDyFK"


# Node Exporter
node_exporter_container_name: node-exporter
node_exporter_container_image: prom/node-exporter:v1.5.0 
node_exporter_container_env: {}
node_exporter_local_port: 9100
node_exporter_container_stop_timeout: "30"

# promtail
promtail_dir: "/etc/promtail"
promtail_config_file_path: "{{promtail_dir}}/promtail.yml"
promtail_docker_imagename: grafana/promtail
promtail_docker_version: 2.8.8
promtail_http_listen_port: 9080
promtail_gRPC_port: 36543
loki_basic_auth_user: "dataops"
loki_basic_auth_password: "dataops"

# prometheus
container_name_prometheus: prometheus
prometheus_container_imagename: prom/prometheus
prometheus_container_image_tag: latest
prometheus_config_container_dir: /etc/prometheus
metrics_auth_user: dataops
prometheus_web_port: 9090
prometheus_config_dir: "{{base_dir}}/prometheus"
prometheus_target_dir: "{{prometheus_config_dir}}/targets"
prometheus_target_project_name: sftp-platform
target_template: "targets.yml"
rules_template: "rules.yml"
target_group: "all"
alertmanager_url: 127.0.0.1:{{alertmanager_web_port}}

# alert manager
alertmanager_container_name: alertmanager
alertmanager_image_tag: latest
alertmanager_web_port: 9095
alert_manager_home_dir_default: /home/{{bootstrap_user}}
alertmanager_config_dir: "{{ alert_manager_home_dir_default }}/alertmanager"
alertmanager_config_file: "alertmanager.yml"
alertmanager_rule_template: "alertmanager.yml"
slack_wehbook: "https://hooks.slack.com/services/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"
slack_channel: "#platform-alerts"

# Loki
loki_dir: "/etc/loki"
loki_data_dir: "/data/loki"
loki_rules_directory: "/data/loki/rules"
loki_docker_image: grafana/loki
loki_docker_version: latest
loki_http_listen_port: 3100

# grafana
grafana_image: "grafana/grafana-enterprise"
grafana_image_tag: latest
grafana_container_name: "grafana"
grafana_base_dir: "/home/{{ ansible_user }}/grafana"
grafana_data_dir: "{{ grafana_base_dir }}/data"
grafana_config_dir: "{{ grafana_base_dir }}/config"
grafana_provisioning_base_dir: "{{ grafana_base_dir }}/provisioning/"
provisoning_dashboard_dir: "{{ grafana_provisioning_base_dir }}/dashboards"
provisoning_datasource_dir: "{{ grafana_provisioning_base_dir }}/datasources"
grafana_dashboards_dir: "{{ grafana_base_dir }}/dashboards"
grafana_port: "3000"
grafana_admin_user: "dataops"
grafana_admin_password: "dataops"  
device: device
grafana_prometheus_datasource: prometheus
