data_source reddit_snowflake_source:
   type: snowflake
   connection:
     username: ${SNOWFLAKE_USER}
     password: ${SNOWFLAKE_PASSWORD}
     account: ${SNOWFlAKE_ACCOUNT}
     database: REDDIT_DATABASE
     warehouse: SODA_WAREHOUSE
     role: SODA_ROLE
     session_parameters:
       QUERY_TAG: soda-queries
       QUOTED_IDENTIFIERS_IGNORE_CASE: false
   schema: staging