server:
  http_listen_port: {{ promtail_http_listen_port }}
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: https://{{ traefik_loki_host }}/loki/api/v1/push
    basic_auth:
      username: "{{ traefik_basic_auth_user }}"
      password: "{{ traefik_basic_auth_password }}"

# local machine logs

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: ["promtail_logging=true"]
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'logstream'
      - source_labels: ['__meta_docker_container_label_scrape_location']
        target_label: 'job'
      - source_labels: ['__meta_docker_container_label_scrape_location']
        target_label: 'scrape_location'
      - source_labels: ['__meta_docker_container_label_instance']
        target_label: 'instance'
      - source_labels: ['__meta_docker_container_label_network']
        target_label: 'network'
      - source_labels: ['__meta_docker_container_label_client_name']
        target_label: 'client_name'
      - source_labels: ['__meta_docker_container_label_group']
        target_label: 'group'
      - source_labels: ['__meta_docker_container_label_host_type']
        target_label: 'host_type'
    