groups:

  - name: AllInstances
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 3m
        labels:
          severity: critical
        annotations:
          summary: Instance {{ $labels.instance }} down
          description: |
            {{ $labels.instance }} of scraper {{ $labels.scrape_location }} has been down for +3 minutes.

      # 1.1.10. Prometheus rule evaluation failures - https://awesome-prometheus-alerts.grep.to/rules#rule-prometheus-self-monitoring-1-10
      # Prometheus encountered {{ $value }} rule evaluation failures, leading to potentially ignored alerts.
      - alert: PrometheusRuleEvaluationFailures
        expr: increase(prometheus_rule_evaluation_failures_total[3m]) > 0
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: Prometheus rule evaluation failures (instance {{ $labels.instance }})
          description: "Prometheus encountered {{ $value }} rule evaluation failures, leading to potentially ignored alerts.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      # 1.2.1. Host out of memory - https://awesome-prometheus-alerts.grep.to/rules#rule-host-and-hardware-1-1
      # Node memory is filling up (< 10% left)
      - alert: HostOutOfMemory
        expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Host out of memory (instance {{ $labels.instance }})
          description: "Node memory is filling up (< 10% left)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      # 1.2.8. Host disk will fill in 24 hours - https://awesome-prometheus-alerts.grep.to/rules#rule-host-and-hardware-1-8
      # Filesystem is predicted to run out of space within the next 24 hours at current write rate
      #
      # Please add ignored mountpoints in node_exporter parameters like
      # "--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|run)($|/)".
      # Same rule using "node_filesystem_free_bytes" will fire when disk fills for non-root users.
      - alert: HostDiskWillFillIn24Hours
        expr: (node_filesystem_avail_bytes * 100) / node_filesystem_size_bytes < 10 and ON (instance, device, mountpoint) predict_linear(node_filesystem_avail_bytes{fstype!~"tmpfs"}[1h], 24 * 3600) < 0 and ON (instance, device, mountpoint) node_filesystem_readonly == 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Host disk will fill in 24 hours (instance {{ $labels.instance }})
          description: "Filesystem is predicted to run out of space within the next 24 hours at current write rate\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      # 1.2.23. Host OOM kill detected
      # OOM kill detected
      # https://awesome-prometheus-alerts.grep.to/rules#rule-host-and-hardware-1-23
      - alert: HostOomKillDetected
        expr: increase(node_vmstat_oom_kill[1m]) > 0
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: Host OOM kill detected (instance {{ $labels.instance }})
          description: "OOM kill detected\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      # 1.2.33. Host requires reboot
      # {{ $labels.instance }} requires a reboot.
      # https://awesome-prometheus-alerts.grep.to/rules#rule-host-and-hardware-1-33
      - alert: HostRequiresReboot
        expr: node_reboot_required > 0
        for: 4h
        labels:
          severity: info
        annotations:
          summary: Host requires reboot (instance {{ $labels.instance }})
          description: "{{ $labels.instance }} requires a reboot.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"