---
- name: start metrics on server
  hosts: all
  gather_facts: true
  become: true
  
  tasks:
    - name: Create Promtail dir
      file:
        path: "{{ promtail_dir }}"
        state: directory

    - name: Promtail config file
      template:
        src: templates/promtail.yml
        dest: "{{ promtail_config_file_path }}"

    # run node exporter
    - name: Run node_exporter container
      community.docker.docker_container:
        name: "{{ node_exporter_container_name }}"
        image: "{{ node_exporter_container_image }}"
        state: started
        restart_policy: always
        stop_timeout: "{{ node_exporter_container_stop_timeout }}"
        ports:
          - "{{ node_exporter_local_port }}:{{ node_exporter_local_port }}"  # Exposes the specified port
        volumes: 
          - /:/rootfs:ro
          - /sys:/host/sys:ro
          - /proc:/host/proc:ro
        env: "{{ node_exporter_container_env }}"
        command: 
          - --path.procfs=/host/proc
          - --path.rootfs=/rootfs
          - --path.sysfs=/host/sys
          - --collector.filesystem.ignored-mount-points
          - '^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker)'
        labels:
          traefik.enable: "true"
          traefik.http.routers.exporter-http.entrypoints: "web"
        networks:
          - name: "airflow_{{ traefik_airflow_server_docker_network }}"
    
    # start promptail
    - name: Start Promtail
      community.docker.docker_container:
        name: promtail
        state: started
        image: "{{ promtail_docker_imagename }}:{{ promtail_docker_version }}"
        labels:
          promtail_logging: "true"
        pull: true
        command: "-config.file={{ promtail_config_file_path }}"
        volumes:
          - "{{ promtail_dir }}:{{ promtail_dir }}"
          - "/var/log:/var/log"
          - /var/lib/docker/containers:/var/lib/docker/containers:ro
          - /var/run/docker.sock:/var/run/docker.sock
        restart_policy: always
        restart: true
        published_ports:
          - "{{ promtail_http_listen_port }}:{{ promtail_http_listen_port }}"  
        log_driver: json-file
        log_options:
          max-file: "10"
          max-size: 30m
          mode: non-blocking
          max-buffer-size: 4m
        networks:
          - name: "airflow_{{ traefik_airflow_server_docker_network }}"
