name: Ansible files & Deployment 

on:
  push:
    paths:
      - 'ansible/playbooks/**'
  pull_request:
    paths:
      - 'ansible/playbooks/**'

jobs:
  build:
    name: Ansible Lint # Naming the build is important to use it as a status check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        # optional (see below):
        with:
          args: "-p ansible/playbooks --config ansible-lint.yaml"
          setup_python: "true"
          requirements_file: "ansible/requirements.yml"

# jobs:
#   ansible-lint:
#     uses: ansible/ansible-content-actions/.github/workflows/ansible_lint.yaml@main
#     with:
#       args: '-p ansible/playbooks --config ansible-lint.yaml'
#       requirements_file: 'ansible/requirements.yml'
