name: Ansible files & Deployment 

on:
  push:
    branches: [main]
    paths:
      - 'ansible/playbooks/**'
  # pull_request:
  #   branches: [main]
  #   paths:
  #     - 'ansible/playbooks/**'

jobs:
  ansible-lint:
    uses: ansible/ansible-content-actions/.github/workflows/ansible_lint.yaml@main
    with:
      args: '-p ansible/playbooks --config ansible-lint.yaml'
      requirements_file: "ansible/requirements.yml"
